spring:
  application:
    name: microservice-client
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.105:8080/eureka
      #defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
  instanceId: ${spring.application.name}:${spri‌​ng.application.insta‌​nce_id:${random.valu‌​e}}
  metadataMap:
    instanceId: ${spring.application.name}:${random.int}