server:
  port: 8090

spring:
  application:
    name: zuul-gateway
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka
      #defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true